### PR TITLE
Add a text summary of the DXVK video tutorial.

### PR DESCRIPTION
**Pull request by JoKeyser**
Hi Lutris team,

this PR offers a text-based summary of the explanation video about DXVK.
I tried not to change the video's content too much, but slightly generalized some specifics (such as the user's home directory), and added some general explanation.
I think it could be phrased even more general, but lets see if you like the idea at all.

In any case, thanks for Lutris, it's awesome.

This would close issue #153 .

### CODE REVIEW

**Comment by kartikynwa** [comment]
Instructions seem correct and make sense to me.

**Comment by psstoyanov** [comment]
@JoKeyser , maybe the instructions can be expanded a bit to add a simple download of the latest CI/CD artifacts from dxvk?

```
### Testing the latest dxvk from master

Find the location of the Lutris runtimes:
$ find . -type d -wholename "*/share/lutris/runtime/dxvk"
./.local/share/lutris/runtime/dxvk
$ cd .local/share/lutris/runtime/dxvk

Create a new folder to use for the desired dxvk version
$ mkdir dxvk-master && cd dxvk-master

Download and extract the artifacts from [dxvk CI/CD](https://github.com/doitsujin/dxvk/actions/workflows/artifacts.yml):
$ wget https://github.com/doitsujin/dxvk/suites/<build_run>/artifacts/<resulting_artifact>
$ unzip dxvk-master-<artifact_version>.zip

Example:
$ wget https://github.com/doitsujin/dxvk/suites/7834588570/artifacts/331388936
$ unzip dxvk-master-084969135b08129f2f262ed0c98610bb6ad3dd11.zip

Remove the zip archive of the artifact
$ rm dxvk-master-<artifact_version>.zip

Set the new manual version in Lutris:
dxvk-master
```

**Comment by JoKeyser** [comment]
@psstoyanov I think that makes sense.

The main goal of this PR is to add any text-based alternative to the video. (I think the video's content is very helpful, but reading it even more helpful.) Once there is agreement to add the text (not sure if there is from the devs?), then of course adding more depth and detail makes sense to me.

**Comment by psstoyanov** [comment]
Thanks, @JoKeyser , I agree that text documentation provides advantages. At least for me, the video wasn't intuitive in its purpose until I already had pre-existing knowledge as of what to look for in it :slightly_smiling_face:  
I hope the addition will make it simpler and ultimately more approachable to other users to provide reliable feedback.

Looking at the other PRs, it would seem @tannisroot is handling the merges - perhaps some directions on where to request for dev feedback could be useful?

**Comment by psstoyanov** [comment]
The above find command I posted,  doesn't work with the Flatpak version.
Should be:
```
$ find . -type d -wholename "*/lutris/runtime/dxvk"
```
This works both on my Manjaro and Steam Deck.

Steam Deck found location:
```
$ find . -type d -wholename "*/lutris/runtime/dxvk"
./.var/app/net.lutris.Lutris/data/lutris/runtime/dxvk
```

Manjaro found location:
```
find . -type d -wholename "*/lutris/runtime/dxvk" 
./.local/share/lutris/runtime/dxvk
```

**Comment by JoKeyser** [comment]
@psstoyanov , thanks for the additions, I'm sure it will help people.
I would also change this PR, but I'm still unsure who to ask for guidance how to merge this finally.

**Comment by strycore** [comment]
I know this is made out of frustration of only having a video version but I think that the reader doesn't need to be indicated that this is a text based documentation. They can see that by themselves. I'm also not sure Lutris should have documentation to compile DXVK because this isn't. 
But also, the docs is this repo aren't official, they are fully community provided and not at all endorsed by the project so you guys do whatever you feel best.

**Pull request merged**
