### PR TITLE
Update WorldOfWarcraft.md

### PR DESCRIPTION
**Pull request by JanGalek**
image

### CODE REVIEW

**Comment by tannisroot** [comment]
This should have a picture that showcases the issue and it should describe in detail what issues the user might experience. "Some graphics problems" is a bit too general.

**Comment by JanGalek** [comment]
It looks like this: 
image

**Comment by tannisroot** [comment]
Can you check if it still looks like this?

**Comment by JanGalek** [comment]
@tannisroot  its ok know. I have AMD Radeon R9 390

**Pull request closed without merging**
